env <- function(dev_type="g", dev_num=4) .Call("create_env", dev_type, dev_num)
type <- function(x) .Call("get_type", x)

dswap <- function(env, x, y) .Call("Dswap", env, x, y)
dscal <- function(env, alpha, x) .Call("Dscal", env, alpha, x)
dcopy <- function(env, x) .Call("Dcopy", env, x)
daxpy <- function(env, alpha, x, y) .Call("Daxpy", env, alpha, x, y)
ddot <- function(env, x, y) .Call("Ddot", env, x, y)
drotg <- function(env, a, b, c, s) .Call("Drotg", env, a, b, c, s)
drot <- function(env, x, y, c, s) .Call("Drot", env, x, y, c, s)
drotmg <- function(env, d1, d2, x, y, param) .Call("Drotmg", env, d1, d2, x, y, param)
drotm <- function(env, x, y, param) .Call("Drotm", env, x, y, param)
dnrm2 <- function(env, x) .Call("Dnrm2", env, x)
idamax <- function(env, x) .Call("iDamax", env, x)
dasum <- function(env, x) .Call("Dasum", env, x)
